// SPDX-License-Identifier: Apache-2.0

"use client";

import { useEffect, useState } from "react";
import { KickerWipe } from "@/components/KickerWipe";
import { Reveal } from "@/components/Reveal";
import { RollingLink } from "@/components/RollingLink";
import { Spotlight } from "@/components/Spotlight";
import { WordReveal } from "@/components/WordReveal";
import { prefersReducedMotion, useInView } from "@/lib/useInView";

// Per-role glyphs in the step-diagram language: a locked ring for the fixed
// rate, a variable wave for yield, paired reserves for liquidity. Each path
// draws itself when the section enters (pathLength + dashoffset transition,
// same mechanism as the card borders).
function Glyph({ role, hidden, delay }: { role: string; hidden: boolean; delay: number }) {
  const draw = (extraDelay = 0): React.CSSProperties => ({
    strokeDasharray: 1,
    strokeDashoffset: hidden ? 1 : 0,
    transition: "stroke-dashoffset 1s cubic-bezier(0.22, 1, 0.36, 1)",
    transitionDelay: `${delay + extraDelay}ms`,
  });
  const common = {
    fill: "none",
    stroke: "#9A9A9A",
    strokeWidth: 1.5,
    pathLength: 1,
  } as const;

  if (role === "fixed") {
    // A ring sealed by a chord: principal, locked to par.
    return (
      <svg viewBox="0 0 64 64" className="h-12 w-12" aria-hidden>
        <circle cx="32" cy="32" r="20" {...common} style={draw()} />
        <path d="M 18 32 H 46" {...common} stroke="#FFFFFF" style={draw(350)} />
      </svg>
    );
  }
  if (role === "yield") {
    // A flat baseline with the variable stream diverging from it.
    return (
      <svg viewBox="0 0 64 64" className="h-12 w-12" aria-hidden>
        <path d="M 10 40 H 54" {...common} style={draw()} />
        <path d="M 10 40 C 24 40 28 22 40 22 C 46 22 50 26 54 18" {...common} stroke="#FFFFFF" style={draw(350)} />
      </svg>
    );
  }
  // Two reserves feeding one pool.
  return (
    <svg viewBox="0 0 64 64" className="h-12 w-12" aria-hidden>
      <circle cx="24" cy="26" r="10" {...common} style={draw()} />
      <circle cx="40" cy="26" r="10" {...common} style={draw(200)} />
      <path d="M 16 46 H 48" {...common} stroke="#FFFFFF" style={draw(450)} />
    </svg>
  );
}

const AUDIENCES = [
  {
    index: "01",
    role: "fixed",
    title: "Fixed-rate buyer",
    body: "Buy PT and hold it to maturity. The principal leg redeems at par while the yield leg remains separate.",
    cta: "Lock a rate",
    href: "/trade",
  },
  {
    index: "02",
    role: "yield",
    title: "Yield trader",
    body: "Buy YT to isolate the yield generated by SY until maturity without buying the principal leg.",
    cta: "Trade yield",
    href: "/trade#buy-yt",
  },
  {
    index: "03",
    role: "pool",
    title: "Liquidity provider",
    body: "Supply PT and SY to one pool. Direct PT swaps and routed YT trades use the same liquidity and pay fees through the same market.",
    cta: "Provide liquidity",
    href: "/pool",
  },
];

export function AudienceCards() {
  const { ref, inView } = useInView<HTMLDivElement>(0.15);
  const [armed, setArmed] = useState(false);

  useEffect(() => {
    if (!prefersReducedMotion()) setArmed(true);
  }, []);

  const hidden = armed && !inView;

  return (
    <section className="relative bg-transparent">
      <div className="mx-auto max-w-[1280px] px-6 py-20 sm:px-16 sm:py-24">
        <KickerWipe className="label-data">Market / Roles</KickerWipe>
        <h2 className="mt-5 text-4xl font-light tracking-tight sm:text-5xl">
          <WordReveal>Who it is for</WordReveal>
        </h2>

        <div ref={ref} className="mt-14 grid gap-4 lg:grid-cols-3 lg:gap-0">
          {AUDIENCES.map((audience, index) => (
            <Spotlight
              key={audience.title}
              className="audience-card relative min-h-[24rem] overflow-hidden bg-white/[0.02] p-8 lg:p-10"
            >
              <svg
                aria-hidden
                className="pointer-events-none absolute inset-0 h-full w-full"
                preserveAspectRatio="none"
                viewBox="0 0 100 100"
              >
                <rect
                  x="0.5"
                  y="0.5"
                  width="99"
                  height="99"
                  fill="none"
                  pathLength="1"
                  stroke="rgba(255,255,255,0.25)"
                  strokeDasharray="1"
                  strokeDashoffset={hidden ? 1 : 0}
                  strokeWidth="1"
                  vectorEffect="non-scaling-stroke"
                  style={{
                    transition: "stroke-dashoffset 1.2s cubic-bezier(0.22, 1, 0.36, 1)",
                    transitionDelay: `${index * 150}ms`,
                  }}
                />
              </svg>

              {/* Watermark index: the step-numeral language, faded to texture. */}
              <span
                aria-hidden
                className="pointer-events-none absolute -right-2 -top-6 text-[9rem] font-light leading-none text-white/[0.05]"
              >
                {audience.index}
              </span>

              <Reveal
                className="relative flex h-full min-h-[20rem] flex-col"
                delay={600 + index * 150}
              >
                <Glyph role={audience.role} hidden={hidden} delay={800 + index * 150} />
                <h3 className="mt-8 text-2xl font-light tracking-tight sm:text-3xl">
                  {audience.title}
                </h3>
                <p className="mt-5 max-w-sm leading-relaxed text-smoke">{audience.body}</p>
                <RollingLink
                  href={audience.href}
                  className="mt-auto pt-10 text-sm text-paper"
                >
                  {`${audience.cta} →`}
                </RollingLink>
              </Reveal>
            </Spotlight>
          ))}
        </div>
      </div>
    </section>
  );
}
