// SPDX-License-Identifier: Apache-2.0

"use client";

import { useEffect, useState } from "react";
import { KickerWipe } from "@/components/KickerWipe";
import { Reveal } from "@/components/Reveal";
import { RollingLink } from "@/components/RollingLink";
import { Spotlight } from "@/components/Spotlight";
import { WordReveal } from "@/components/WordReveal";
import { prefersReducedMotion, useInView } from "@/lib/useInView";

const AUDIENCES = [
  {
    index: "01",
    title: "Fixed-rate buyer",
    body: "Buy PT and hold it to maturity. The principal leg redeems at par while the yield leg remains separate.",
    cta: "Lock a rate",
    href: "/trade",
  },
  {
    index: "02",
    title: "Yield trader",
    body: "Buy YT to isolate the yield generated by SY until maturity without buying the principal leg.",
    cta: "Trade yield",
    href: "/trade#buy-yt",
  },
  {
    index: "03",
    title: "Liquidity provider",
    body: "Supply PT and SY to one pool. Direct PT swaps and routed YT trades use the same liquidity and pay fees through the same market.",
    cta: "Provide liquidity",
    href: "/pool",
  },
];

export function AudienceCards() {
  const { ref, inView } = useInView<HTMLDivElement>(0.15);
  const [armed, setArmed] = useState(false);

  useEffect(() => {
    if (!prefersReducedMotion()) setArmed(true);
  }, []);

  const hidden = armed && !inView;

  return (
    <section className="relative bg-transparent">
      <div className="mx-auto max-w-[1280px] px-6 py-24 sm:px-16 sm:py-32">
        <KickerWipe className="label-data">Market / Roles</KickerWipe>
        <h2 className="mt-5 text-4xl font-light tracking-tight sm:text-5xl">
          <WordReveal>Who it is for</WordReveal>
        </h2>

        <div ref={ref} className="mt-14 grid lg:grid-cols-3">
          {AUDIENCES.map((audience, index) => (
            <Spotlight
              key={audience.title}
              className="relative min-h-[23rem] overflow-hidden p-8 lg:p-10"
            >
              <svg
                aria-hidden
                className="pointer-events-none absolute inset-0 h-full w-full"
                preserveAspectRatio="none"
                viewBox="0 0 100 100"
              >
                <rect
                  x="0.5"
                  y="0.5"
                  width="99"
                  height="99"
                  fill="none"
                  pathLength="1"
                  stroke="rgba(255,255,255,0.18)"
                  strokeDasharray="1"
                  strokeDashoffset={hidden ? 1 : 0}
                  strokeWidth="1"
                  vectorEffect="non-scaling-stroke"
                  style={{
                    transition: "stroke-dashoffset 1.2s cubic-bezier(0.22, 1, 0.36, 1)",
                    transitionDelay: `${index * 150}ms`,
                  }}
                />
              </svg>

              <Reveal
                className="flex h-full min-h-[19rem] flex-col"
                delay={1200 + index * 150}
              >
                <p className="label-data text-white/30">{audience.index}</p>
                <h3 className="mt-8 text-2xl font-light tracking-tight sm:text-3xl">
                  {audience.title}
                </h3>
                <p className="mt-5 max-w-sm leading-relaxed text-smoke">{audience.body}</p>
                <RollingLink
                  href={audience.href}
                  className="mt-auto pt-10 text-sm text-paper"
                >
                  {`${audience.cta} →`}
                </RollingLink>
              </Reveal>
            </Spotlight>
          ))}
        </div>
      </div>
    </section>
  );
}
