// SPDX-License-Identifier: Apache-2.0

import Link from "next/link";
import { StepNumeral } from "@/components/StepNumeral";
import { HeroBackground } from "@/components/HeroBackground";
// The three token legs, defined in the protocol's own terms. No invented
// financial figures (AGENTS section 7): the stats band states protocol facts,
// not market numbers, so the page reads honestly before a market is deployed.
const LEGS = [
  {
    tag: "SY",
    name: "Standardized Yield",
    body: "The wrapped yield-bearing asset. SY standardizes a Blend USDC position into a single, yield-accruing share.",
  },
  {
    tag: "PT",
    name: "Principal Token",
    body: "The principal, isolated. PT redeems 1:1 for the underlying at maturity. Buy it at a discount to lock a fixed rate.",
  },
  {
    tag: "YT",
    name: "Yield Token",
    body: "The yield, isolated. YT streams all yield generated by the SY until maturity, for speculation or hedging.",
  },
];

const STEPS = [
  {
    n: "01",
    title: "Deposit and mint",
    kicker: "Action / Supply",
    body: "Deposit USDC. The protocol wraps it into Standardized Yield, ready for the splitting mechanism.",
    band: "ink" as const,
  },
  {
    n: "02",
    title: "Split",
    kicker: "Mechanism / Fracture",
    body: "SY fractures into two parts. The principal is secured as PT, the yield is isolated as YT.",
    band: "carbon" as const,
  },
  {
    n: "03",
    title: "Trade or hold",
    kicker: "Outcome / Market",
    body: "Hold PT to maturity for a fixed return, or trade either leg on a time-decay AMM priced by an internal TWAP.",
    band: "ink" as const,
  },
];

// Protocol facts, stated as oversized numerals. These are design choices that
// hold regardless of deployment, not market metrics.
const FACTS = [
  { value: "01", label: "Active market", note: "Blend USDC", signal: false },
  { value: "03", label: "Token legs", note: "SY · PT · YT", signal: false },
  { value: "00", label: "Price oracles", note: "Internal TWAP", signal: false },
  { value: "1:1", label: "PT at maturity", note: "Redeems to par", signal: false },
];

// Monochrome diagrams for each step. Amber is reserved for live/active signals,
// so these stay paper/ash only (no decorative accent), per the single-accent rule.
function StepDiagram({ n }: { n: string }) {
  if (n === "01") {
    return (
      <svg viewBox="0 0 240 240" className="h-48 w-48" aria-hidden="true">
        <circle cx="120" cy="120" r="92" fill="none" stroke="#6D6D6D" strokeWidth="1" />
        <circle cx="120" cy="120" r="46" fill="#FFFFFF" />
      </svg>
    );
  }
  if (n === "02") {
    return (
      <svg viewBox="0 0 320 160" className="h-40 w-72" aria-hidden="true">
        <line x1="60" y1="80" x2="260" y2="80" stroke="#6D6D6D" strokeWidth="1" />
        <circle cx="60" cy="80" r="34" fill="none" stroke="#6D6D6D" strokeWidth="1" />
        <circle cx="160" cy="80" r="28" fill="#FFFFFF" />
        <circle cx="260" cy="80" r="34" fill="none" stroke="#9A9A9A" strokeWidth="1" />
        <circle cx="260" cy="80" r="5" fill="#9A9A9A" />
      </svg>
    );
  }
  return (
    <svg viewBox="0 0 320 120" className="h-32 w-72" aria-hidden="true">
      <line x1="30" y1="60" x2="290" y2="60" stroke="#6D6D6D" strokeWidth="1" />
      <circle cx="30" cy="60" r="6" fill="#FFFFFF" />
      <circle cx="290" cy="60" r="6" fill="#9A9A9A" />
      <text x="30" y="92" fill="#6D6D6D" fontSize="13" textAnchor="middle">PT fixed</text>
      <text x="290" y="92" fill="#6D6D6D" fontSize="13" textAnchor="middle">YT variable</text>
    </svg>
  );
}

export default function LandingPage() {
  return (
    <>
      {/* Hero: clean ink editorial frame, no atmospheric render. The headline
          carries the section; the metallic background lives on the app screens. */}
      <section className="relative flex min-h-screen flex-col justify-center overflow-hidden">
                <HeroBackground />
        <div className="relative mx-auto w-full max-w-[1280px] px-6 sm:px-16">
          <h1 className="max-w-4xl text-5xl font-light leading-[1.02] tracking-tight sm:text-7xl lg:text-8xl">
            Split Stellar yield into principal and yield.
          </h1>
          <p className="mt-8 max-w-xl text-lg leading-relaxed text-smoke">
            Deposit USDC. Mint SY. Separate fixed principal from variable yield, and trade both.
          </p>
          <div className="mt-10 flex flex-col items-start gap-5 sm:flex-row sm:items-center">
            <Link
              href="/trade"
              className="rounded-pill bg-paper px-7 py-3 text-[13px] font-semibold uppercase tracking-[0.12em] text-ink transition hover:bg-smoke"
            >
              Launch App
            </Link>
            <span className="font-mono text-sm tracking-[0.2em] text-ash">
              Blend USDC · 3-month maturity
            </span>
          </div>
        </div>
        <div className="absolute bottom-8 left-6 flex items-center gap-3 sm:left-16">
          <span className="label-data">Scroll</span>
          <span className="h-px w-10 bg-ash" />
        </div>
      </section>

      {/* Invariant band: the equation, on a paper-white block, with token legs. */}
      <section id="protocol" className="bg-paper text-ink">
        <div className="mx-auto max-w-[1280px] px-6 py-24 sm:px-16 sm:py-32">
          <p className="text-center text-4xl font-light tracking-tight sm:text-6xl">PT + YT = SY</p>
          <div className="mt-20 grid border-t border-black/15 sm:grid-cols-3">
            {LEGS.map((leg, i) => (
              <div
                key={leg.tag}
                className={`border-t border-black/15 py-8 sm:border-t-0 sm:px-10 ${
                  i < LEGS.length - 1 ? "sm:border-r sm:border-black/15" : ""
                } ${i === 0 ? "sm:pl-0" : ""}`}
              >
                <h3 className="text-2xl font-light tracking-tight sm:text-3xl">
                  {leg.name} <span className="text-graphite">({leg.tag})</span>
                </h3>
                <p className="mt-4 max-w-sm leading-relaxed text-graphite">{leg.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works: editorial 01/02/03 steps in alternating bands, each with
          a monochrome diagram, oversized numerals, and the kicker label. */}
      <section id="how-it-works">
        {STEPS.map((step) => (
          <div
            key={step.n}
            className={step.band === "carbon" ? "bg-carbon" : "bg-ink"}
          >
            <div className="mx-auto grid max-w-[1280px] items-center gap-10 px-6 py-24 sm:px-16 lg:grid-cols-2">
              <div>
                <StepNumeral>{step.n}</StepNumeral>
                <h2 className="mt-6 text-3xl font-light tracking-tight sm:text-4xl">{step.title}</h2>
                <p className="mt-2 label-data">{step.kicker}</p>
                <p className="mt-6 max-w-md leading-relaxed text-smoke">{step.body}</p>
              </div>
              <div className="flex justify-center lg:justify-end">
                <StepDiagram n={step.n} />
              </div>
            </div>
          </div>
        ))}
      </section>

      {/* Protocol overview: facts as numerals in an enclosed panel, not invented
          market metrics. */}
      <section className="border-t border-white/10 bg-ink">
        <div className="mx-auto max-w-[1280px] px-6 py-24 sm:px-16">
          <div className="flex items-center justify-between">
            <h2 className="text-3xl font-light tracking-tight">Protocol overview</h2>
            <p className="label-data text-amber">Live · Testnet</p>
          </div>
          <div className="mt-12 grid grid-cols-2 border border-white/10 lg:grid-cols-4">
            {FACTS.map((fact, i) => (
              <div
                key={fact.label}
                className={`p-8 ${i < FACTS.length - 1 ? "border-b border-white/10 lg:border-b-0 lg:border-r" : ""} ${
                  i < 2 ? "border-b lg:border-b-0" : ""
                }`}
              >
                <p
                  className={`text-5xl font-light tabular-nums tracking-tight sm:text-6xl ${
                    fact.signal ? "text-amber" : "text-paper"
                  }`}
                >
                  {fact.value}
                </p>
                <p className="mt-4 label-data">{fact.label}</p>
                <p className="mt-1 text-sm text-pewter">{fact.note}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
